---
- name: Install curl, locales and apt-transport-https
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - curl
    - locales
    - apt-transport-https
    - sshpass
    - build-essential

- name: Configure Locale as en_US.UTF-8
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Add /etc/hosts entries in DevSecOps-Box
  ansible.builtin.include_tasks: hosts_entry.yml
