---

- name: Setup the Git repo
  ansible.builtin.git:
    name: "{{ item.url }}"
    dest: "/home/vagrant/{{ item.dest }}"
    version: master
    update: no
  with_items:
    - { url : 'https://github.com/dev-sec/ansible-os-hardening.git', dest: 'ansible-os-hardening' }
    - { url : 'https://github.com/djuhnix/devsecops-studio.git', dest: 'devsecops-studio' }
    - { url : 'https://github.com/dev-sec/linux-baseline.git', dest: 'linux-baseline.git' }
    - { url : 'https://github.com/dev-sec/cis-docker-benchmark.git', dest: 'cis-docker-benchmark.git' }
  become: yes
  become_user: vagrant
