---

- name: Install awscli, awsebcli, ansible, ansible-lint
  ansible.builtin.pip:
    name: "{{ item }}"
  with_items:
    - awscli
    - awsebcli
    - ansible
    - ansible-lint

- name: Install tree package
  ansible.builtin.apt:
    name: tree
    state: present

- name: Generate SSH key of vagrant user
  ansible.builtin.user:
    name: vagrant
    generate_ssh_key: "yes"
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Clone git repos of needed code
  ansible.builtin.import_tasks: git_repos.yml

- name: Clone git repos of needed code
  ansible.builtin.import_tasks: docker.yml
  when: docker_package_state == "present"
