---
- src: geerlingguy.pip
  version: 1.1.0
- src: geerlingguy.ruby
  version: 2.4.3
- src: geerlingguy.docker
  version: 1.2.0
- src: geerlingguy.ansible-role-packer
  version: 1.0.0
- src: geerlingguy.nginx
  version: 1.14.0
- src: geerlingguy.elasticsearch
  version: 2.1.3
- src: geerlingguy.kibana
  version: 2.0.1
- src: geerlingguy.logstash
  version: 3.0.0
- src: geerlingguy.java
  version: 1.7.4
- src: geerlingguy.jenkins
  version: 3.5.0
- src: rvm_io.ruby
  version: 2.6.3
- src: secfigo.terraform
  version: 1.0.0
- src: secfigo.gauntlt
  version: master
