---
- name: Install dependencies
  ansible.builtin.package: name=unzip

- name: Download Selenium
  ansible.builtin.get_url:
    url: "http://selenium-release.storage.googleapis.com/{{ selenium_version | regex_replace('\\.[0-9]+$', '') }}/selenium-server-standalone-{{ selenium_version }}.jar"
    dest: "selenium-server-standalone-{{ selenium_version }}.jar"

- name: Install firefox
  ansible.builtin.apt:
    name=firefox
    state=present
    update_cache=yes
