---

- name: Install gitlab runner
  hosts: all
  become: true
  become_user: root
  remote_user: root
  vars:
    gitlab_runner_registration_token: ''
    gitlab_runner_connect_enable: false

    #Gauntlt needs ruby installed
    ruby_version: 'ruby-2.3.1'
    rvm1_rubies: ['{{ ruby_version }}']
    rvm1_user: 'root'
    rvm1_install_path: '/usr/local/rvm'

    # Docker settings for runner
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_package_state: present

    # Docker compose
    docker_install_compose: true
    docker_compose_version: "1.16.1"
    docker_compose_path: /usr/local/bin/docker-compose

    docker_apt_release_channel: stable
    docker_apt_repository: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"

    # Packer
    packer_version: "1.1.0"
    packer_arch: "amd64"
    packer_bin_path: /usr/local/bin


  roles:
    - common
    - rvm.ruby
    - secfigo.gauntlt
    - geerlingguy.docker
    - gitlab-runner
    - geerlingguy.packer
  tags:
    - runner
