---

- name: Check if GitLab Runner /etc directory is created
  ansible.builtin.stat: path=/etc/gitlab-runner
  register: gitlab_config_dir

- name: Check if GitLab Runner Configuragion file is present
  ansible.builtin.stat: path=/etc/gitlab-runner
  register: gitlab_config_file

- name: Check if GitLab Runner is already installed.
  ansible.builtin.stat: path=/usr/bin/gitlab-runner
  register: gitlab_runner_file

- name: Download GitLab Runner repository installation script.
  ansible.builtin.get_url:
    url: "{{ gitlab_runner_repository_installation_script_url }}"
    dest: /tmp/gitlab_runner_install_repository.sh
    validate_certs: yes
  when: (gitlab_runner_file.stat.exists == false)

- name: Install GitLab Runner repository
  ansible.builtin.command: bash /tmp/gitlab_runner_install_repository.sh
  when: (gitlab_runner_file.stat.exists == false)

- name: Install GitLab Runner dependencies
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  with_items:
    - debian-archive-keyring
    - apt-transport-https
    - ca-certificates

- name: Install GitLab Runner
  ansible.builtin.apt:
    name: gitlab-runner
    state: present

- name: Create required directory
  ansible.builtin.file:
    path: "{{ gitlab_runner_persistent_dir }}"
    state: directory
    owner: gitlab-runner
    group: gitlab-runner
    mode: 0775
    recurse: true
  when: (gitlab_config_dir.stat.exists == false)

- name: Copy config.toml to /etc/gitlab-runner
  ansible.builtin.template:
    src: config.toml.j2
    dest: /etc/gitlab-runner/config.toml
    owner: root
    group: root
    mode: 0644
  when: (gitlab_config_file.stat.exists == false)

- name: Install Self-Signed cert on system
  ansible.builtin.include_tasks: custom-certs.yml
  when: gitlab_runner_connect_enable == true

- name: Wait untils Gitlab web API is available
  ansible.builtin.uri:
    url: '{{ gitlab_runner_coordinator_url }}'
    method: GET
    validate_certs: no
  register: result
  until: result.status != 302
  retries: 12
  delay: 5
  when: gitlab_runner_connect_enable == true

- name: Check whether /etc/hosts contains "10.0.1.15 gitlab.local"
  ansible.builtin.command: awk /gitlab.local$/ /etc/hosts
  register: hosts_content
  changed_when: False

  # https://gitlab.com/gitlab-org/gitlab-runner/issues/1490
- name: Add gitlab.local ip address into /etc/hosts
  ansible.builtin.shell: echo "10.0.1.15 gitlab.local" >> /etc/hosts
  when: "'10.0.1.15 gitlab.local' not in hosts_content.stdout"

- name: Register GitLab Runner
  ansible.builtin.include_tasks: register-runner.yml
  when: gitlab_runner_connect_enable == true

- name: Setup docker with self signed ssl
  ansible.builtin.include_tasks: docker.yml
  when: docker_package_state == "present"
