---

- name: Install gitlab runner
  hosts: all
  become: true
  become_user: root
  remote_user: vagrant
  vars:
    gitlab_runner_registration_token: 'CtNi9vq-4yFazTLntDU-'
    gitlab_runner_connect_enable: false

    # GitLab Runner
    gauntlt_version: "1.0.13"

    #Gauntlt needs ruby installed
    ruby_version: 'ruby-3.3.0'
    rvm1_rubies: ['{{ ruby_version }}']
    rvm1_user: 'root'
    rvm1_install_path: '/usr/local/rvm'

    # Docker settings for runner
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_package_state: "present"

    # Docker compose
    docker_install_compose: true
    docker_compose_version: "1.16.1"
    docker_compose_path: /usr/local/bin/docker-compose

    docker_apt_release_channel: stable
    docker_apt_repository: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"

    # Packer
    packer_version: "1.1.0"
    packer_arch: "amd64"
    packer_bin_path: /usr/local/bin

    # host entries won't work in docker
    # see https://stackoverflow.com/questions/28327458/how-to-add-my-containers-hostname-to-etc-hosts
    add_host_entries: true

  roles:
    - common # need curl for rvm.ruby
    - rvm.ruby
    - secfigo.gauntlt
    - geerlingguy.docker
    - gitlab-runner
    - geerlingguy.packer
    - cli-tools
  tags:
    - runner
