---

- name: Install Security Tools
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  with_items:
    - nikto
    - nmap
    - sqlmap
    - python-pip
    - virtualenv

- name: Install tools via pip
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  with_items:
    - sslyze
    - ansible
