---

- name: Install gauntlt missing dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - g++
    - ruby-dev

- name: Setup docker with self signed ssl
  ansible.builtin.include_tasks: docker.yml
  when: docker_package_state == "present"

- name: Add gitlab self signed ssl to trust store
  ansible.builtin.include_tasks: custom-certs.yml
